// GENERATED by scripts/capture-screens.mjs — do not edit by hand.
// Frames of the hero drill-down and the on-screen position of each tap,
// as a percentage of the 390×844 capture.
export const SCREEN = {"width":390,"height":844} as const

export interface HeroFrame {
  file: string
  tap: { x: number; y: number; w: number; h: number; label: string } | null
}

export const HERO_FRAMES: HeroFrame[] = [
  {
    "file": "vestibular-flow",
    "tap": {
      "x": 18.89,
      "y": 59.66,
      "w": 29.57,
      "h": 4.9,
      "label": "Peripheral"
    }
  },
  {
    "file": "vestibular-peripheral",
    "tap": {
      "x": 12.82,
      "y": 38.74,
      "w": 17.44,
      "h": 3.41,
      "label": "Idiopathic vestibular"
    }
  },
  {
    "file": "vestibular-idiopathic",
    "tap": null
  }
]
