// GENERATED by scripts/capture-screens.mjs — do not edit by hand.
// Each sequence is a real drill-down captured from the app: the frames, and
// the on-screen position of the tap that led to the next one, as a
// percentage of the 390×844 capture.
export const SCREEN = {"width":390,"height":844} as const

/** The part of each capture the homepage frames, in capture pixels. */
export const VISIBLE_HEIGHT = 560

export interface SequenceFrame {
  file: string
  tap: { x: number; y: number; w: number; h: number; label: string } | null
}

export interface ScreenSequence {
  /** Alt text: what a reader who cannot see the replay is told. */
  label: string
  frames: SequenceFrame[]
}

export type SequenceName = 'vestibular' | 'dx-approach' | 'mix-match' | 'protocol'

export const SEQUENCES: Record<SequenceName, ScreenSequence> = {
  "vestibular": {
    "label": "Vetic on a phone: the Acute Vestibular flow, tapping through to the peripheral causes and then to the Idiopathic Vestibular Disease page.",
    "frames": [
      {
        "file": "vestibular-flow",
        "tap": {
          "x": 18.89,
          "y": 56.71,
          "w": 29.57,
          "h": 4.9,
          "label": "Peripheral"
        }
      },
      {
        "file": "vestibular-peripheral",
        "tap": {
          "x": 13.46,
          "y": 41.35,
          "w": 18.72,
          "h": 3.41,
          "label": "Idiopathic vestibular"
        }
      },
      {
        "file": "vestibular-idiopathic",
        "tap": null
      }
    ]
  },
  "dx-approach": {
    "label": "Vetic on a phone: the Acute Myelopathy diagnostic approach, moving from the History tab through Exam to Diagnostics.",
    "frames": [
      {
        "file": "myelopathy-history",
        "tap": {
          "x": 50,
          "y": 16.62,
          "w": 29.92,
          "h": 2.68,
          "label": "🩺 Exam"
        }
      },
      {
        "file": "myelopathy-exam",
        "tap": {
          "x": 80.94,
          "y": 16.62,
          "w": 29.91,
          "h": 2.68,
          "label": "🔬 Diagnostics"
        }
      },
      {
        "file": "myelopathy-diagnostics",
        "tap": null
      }
    ]
  },
  "mix-match": {
    "label": "Vetic on a phone: three vestibular signs entered into Mix & Match, narrowed to the dog, then one differential opened.",
    "frames": [
      {
        "file": "mix-match-signs",
        "tap": {
          "x": 50,
          "y": 28.79,
          "w": 27.35,
          "h": 3.79,
          "label": "🐕 Dog"
        }
      },
      {
        "file": "mix-match-results",
        "tap": {
          "x": 39.21,
          "y": 18.84,
          "w": 61.49,
          "h": 2.13,
          "label": "Canine Distemper Virus Encephalitis"
        }
      },
      {
        "file": "mix-match-disease",
        "tap": null
      }
    ]
  },
  "protocol": {
    "label": "Vetic on a phone: the Diabetic Ketoacidosis disease page, opening its emergency protocol with the doses attached.",
    "frames": [
      {
        "file": "dka-disease",
        "tap": {
          "x": 48.15,
          "y": 51.24,
          "w": 79.38,
          "h": 4.86,
          "label": "🚨 Emergency protocol: Diabetic Ketoacidosis (DKA) — Management Protocol"
        }
      },
      {
        "file": "dka-protocol",
        "tap": null
      }
    ]
  }
}
