// ── Vomiting — diagnostic approach (data) ───────────────────────────────────
// Migration of vomiting{History,Exam,Dx}Html (legacy HTML consts in
// ../vomiting.ts) to the typed DxApproach model. Rendered by renderDxApproach.

import type { DxApproach } from '../dxTypes'
import { stepTable, bullets } from './shared/dxHelpers'

export const vomitingDx: DxApproach = {
  sign: 'vomiting',
  title: 'Vomiting',
  tabs: {

  history: {
    title: 'History: Vomiting',
    blocks: [
      { kind: 'step', text: '📋 STEP 1 — VOMITING vs REGURGITATION?', noArrowAfter: true },
      {
        kind: 'gridTable',
        cols: '1.2fr 1fr 1fr',
        dividers: true,
        headers: ['Feature', { text: 'Vomiting', tone: 'danger' }, { text: 'Regurgitation', tone: 'green' }],
        rows: [
          ['Retching?', { text: 'Usually present', tone: 'danger' }, { text: 'Usually absent', tone: 'green' }],
          ['Abdominal effort?', { text: 'Active', tone: 'danger' }, { text: 'Passive — none', tone: 'green' }],
          ['Prodromal nausea?', { text: 'Lip licking, ptyalism', tone: 'danger' }, { text: 'Absent', tone: 'green' }],
          ['Bile present?', { text: 'May be present', tone: 'danger' }, { text: 'Usually absent', tone: 'green' }],
          ['Ingesta digested?', { text: 'May be digested', tone: 'danger' }, { text: 'Typically undigested, tubular', tone: 'green' }],
          ['Timing after eating?', { text: 'Variable', tone: 'danger' }, { text: 'Any time; soon after ↑ suspicion', tone: 'green' }],
          ['White/clear mucus?', { text: 'Less typical', tone: 'danger' }, { text: 'Frothy saliva common', tone: 'green' }],
          ['Frequency?', { text: 'Variable', tone: 'danger' }, { text: 'Many/day, no systemic signs', tone: 'green' }],
          ['Duration?', { text: 'Variable', tone: 'danger' }, { text: bullets(['Weeks–months (megaoesoph.)', 'Acute if obstructive']), tone: 'green' }],
        ],
      },
      { kind: 'note', html: `⚠️ If uncertain, work up as <strong>vomiting</strong>. If the vomiting workup yields no diagnosis, pursue oesophageal investigation. Owner video is very helpful.` },

      { kind: 'step', text: '📖 STEP 2 — AETIOLOGICAL CLUES: CHRONICITY', noArrowAfter: true },
      {
        kind: 'gridTable',
        label: 'Acute vomiting (<7 days)',
        cols: '0.8fr 1.35fr',
        dividers: true,
        headers: ['Cause', { text: 'Detail', tone: 'teal' }],
        rows: [
          ['<strong>Dietary indiscretion</strong>', { text: 'Most common cause in dogs', tone: 'green' }],
          ['<strong>Toxin ingestion</strong>', { text: bullets(['Ethylene glycol', 'Chocolate', 'Lilies', 'Grapes', 'Xylitol', 'Lead']), tone: 'green' }],
          ['<strong>Drug-induced</strong>', { text: bullets(['NSAIDs', 'Antibiotics', 'Chemotherapy', 'Opioids', 'Xylazine (🐱)']), tone: 'green' }],
          ['<strong>Infectious gastroenteritis</strong>', { text: bullets(['Parvovirus', 'Panleukopenia — young unvaccinated']), tone: 'green' }],
          ['<strong>Foreign body</strong>', { text: 'Especially young animals + known pica', tone: 'green' }],
          ['<strong>GDV</strong>', { text: '<strong>Emergency</strong> — acute distension + non-productive retching in a large breed dog', tone: 'danger' }],
          ['<strong>Intussusception</strong>', { text: bullets(['Animals &lt;1 year', 'Often concurrent diarrhoea + haematochezia']), tone: 'green' }],
          ['<strong>Acute pancreatitis</strong>', { text: 'Cranial abdominal pain common', tone: 'green' }],
        ],
      },
      { kind: 'note', html: `Many acute cases are self-limiting. <strong>Red flags require urgent workup.</strong>` },
      {
        kind: 'gridTable',
        label: 'Chronic vomiting (>7 days)',
        cols: '0.8fr 1.35fr',
        dividers: true,
        headers: ['Cause', { text: 'Detail', tone: 'teal' }],
        rows: [
          ['<strong>Chronic enteropathy / IBD</strong>', { text: 'Commonest chronic primary GI cause', tone: 'warning' }],
          ['<strong>GI neoplasia</strong>', { text: bullets(['Lymphoma', 'Adenocarcinoma', 'Mast cell tumour', 'Gastrinoma']), tone: 'warning' }],
          ['<strong>Food allergy or intolerance</strong>', { text: 'Dietary trial required to confirm', tone: 'warning' }],
          ['<strong>Motility disorder / delayed gastric emptying</strong>', { text: 'Vomiting food hours after eating', tone: 'warning' }],
          ['<strong><em>Helicobacter</em> spp.</strong>', { text: 'Clinical significance variable', tone: 'warning' }],
          ['<strong>Systemic / metabolic</strong>', { text: bullets(['CKD', 'Hepatic disease', 'Hyperthyroidism (🐱)', 'Hypoadrenocorticism']), tone: 'warning' }],
          ['<strong>Structural</strong>', { text: bullets(['Hiatal hernia', 'Pyloric stenosis', 'Gastric antral hypertrophy']), tone: 'warning' }],
          ['<strong>Pancreatitis</strong>', { text: 'Chronic / recurrent', tone: 'warning' }],
        ],
      },
      { kind: 'note', html: `Requires a systematic minimum database + targeted second-tier diagnostics.` },

      { kind: 'step', text: '📖 STEP 3 — CHARACTER OF VOMITUS', noArrowAfter: true },
      {
        kind: 'gridTable',
        cols: '0.8fr 1.35fr',
        dividers: true,
        headers: ['Character', { text: 'Means', tone: 'teal' }],
        rows: [
          ['<strong>Frank red blood</strong> (haematemesis)', { text: bullets(['Active upper GI haemorrhage — ulceration', 'Neoplasia', 'Coagulopathy']), tone: 'danger' }],
          ['<strong>"Coffee grounds"</strong>', { text: 'Slow upper GI haemorrhage', tone: 'danger' }],
          ['<strong>Blood — caveat</strong>', { text: 'Swallowed blood from a nasal / oral / pulmonary source can mimic haematemesis', tone: 'danger' }],
          ['<strong>Bile</strong>', { text: 'Gastric outflow problem, or intestinal dysmotility with duodenogastric reflux', tone: 'warning' }],
          ['<strong>Pyloric outflow obstruction</strong>', { text: 'Bile usually <strong>absent</strong> — no communication with the duodenum', tone: 'warning' }],
          ['<strong>Bilious vomiting syndrome</strong>', { text: 'Small amounts of bile after prolonged fasting → duodenogastric reflux at the end of the fasting window', tone: 'warning' }],
          ['<strong>Undigested / partially digested food, hours after eating</strong>', { text: 'Motility disorder or gastric outflow obstruction', tone: 'green' }],
          ['<strong>Food immediately / soon after eating</strong>', { text: bullets(['Anxiety', 'Oesophageal disease', 'Obstructive lesion']), tone: 'green' }],
        ],
      },

      { kind: 'step', text: '🐾 STEP 4 — KEY SIGNALMENT + EXPOSURE CLUES', noArrowAfter: true },
      {
        kind: 'gridTable',
        label: 'Signalment',
        cols: '0.8fr 1.35fr',
        dividers: true,
        headers: ['Signalment', { text: 'Points to', tone: 'teal' }],
        rows: [
          ['<strong>Young (unvaccinated)</strong>', { text: bullets(['Parvovirus', 'Panleukopenia', 'Intussusception', 'FB', 'Parasites']), tone: 'green' }],
          ['<strong>Older</strong>', { text: bullets(['Neoplasia (GI or extra-GI)', 'Hyperthyroidism (🐱)', 'CKD']), tone: 'green' }],
          ['<strong>Brachycephalic</strong>', { text: bullets(['Pyloric stenosis', 'Hiatal hernia']), tone: 'warning' }],
          ['<strong>Shar Pei / German Shepherd / Rottweiler</strong>', { text: 'IBD', tone: 'warning' }],
          ['<strong>Large / giant breed</strong>', { text: '<strong>GDV</strong> — emergency if acute distension', tone: 'danger' }],
          ['<strong>Miniature Schnauzer</strong>', { text: 'Dyslipidaemia → pancreatitis', tone: 'warning' }],
          [bullets(['<strong>Nova Scotia Duck Tolling Retriever</strong>', '<strong>Great Dane</strong>', '<strong>WHWT</strong>']), { text: 'Hypoadrenocorticism', tone: 'warning' }],
          ['<strong>Siamese cat</strong>', { text: bullets(['GI adenocarcinoma', 'Intussusception']), tone: 'warning' }],
          ['<strong>Intact female</strong>', { text: '<strong>Pyometra</strong> — always consider if not neutered', tone: 'danger' }],
        ],
      },
      {
        kind: 'gridTable',
        label: 'Drug / toxin / vaccination · travel · concurrent signs',
        cols: '0.8fr 1.35fr',
        dividers: true,
        headers: ['History', { text: 'Significance', tone: 'teal' }],
        rows: [
          ['<strong>NSAIDs</strong>', { text: 'Gastric erosion / ulceration — <strong>discontinue immediately if vomiting</strong>', tone: 'info' }],
          ['<strong>Other drugs</strong>', { text: bullets(['Antibiotics', 'Chemotherapy', 'Opioids', 'Cyclosporine', 'Mycophenolate', 'Xylazine (🐱)']), tone: 'info' }],
          ['<strong>Toxins</strong>', { text: bullets(['Ethylene glycol', 'Ethanol', 'Theobromine', 'Lilies (🐱)', 'Xylitol', 'Grapes']), tone: 'info' }],
          ['<strong>Incomplete vaccination</strong>', { text: 'Parvovirus / panleukopenia remain on the differential', tone: 'info' }],
          ['<strong>Travel — endemic area</strong>', { text: bullets(['Histoplasmosis (concurrent diarrhoea · weight loss · lung signs)', '<em>Pythium insidiosum</em> in Gulf Coast / tropical regions (GI mass · weight loss)']), tone: 'violet' }],
          ['<strong>Concurrent diarrhoea</strong>', { text: 'Ileal / jejunal / colonic involvement', tone: 'warning' }],
          ['<strong>Weight loss + hyporexia</strong>', { text: 'Diffuse GI disease or systemic illness', tone: 'warning' }],
          ['<strong>Neurological signs</strong>', { text: bullets(['CNS / vestibular cause — motion sickness', 'Intracranial disease']), tone: 'warning' }],
          ['<strong>Intact female + systemic illness</strong>', { text: '<strong>Pyometra</strong> — even without PU/PD', tone: 'danger' }],
        ],
      },
    ],
    after: [{ kind: 'disclaimer' }],
  },

  exam: {
    title: 'Exam: Vomiting',
    blocks: [
      { kind: 'step', text: '🩺 PHYSICAL EXAMINATION', noArrowAfter: true },
      {
        kind: 'gridTable',
        label: 'Temperature · hydration · cardiovascular · mucous membranes',
        cols: '0.8fr 1.35fr',
        dividers: true,
        headers: ['Finding', { text: 'Points to', tone: 'teal' }],
        rows: [
          ['<strong>Fever</strong>', { text: bullets(['Infectious gastroenteritis', 'Aspiration pneumonia', 'Septic peritonitis', 'Pyometra. <em>Absence of fever does not exclude serious disease</em>']), tone: 'green' }],
          ['<strong>Hypothermia</strong>', { text: bullets(['Shock', 'Hypoadrenocorticism', 'Severe systemic disease']), tone: 'green' }],
          ['<strong>Hydration</strong>', { text: bullets(['Skin turgor', 'Mucous membrane moisture', 'Capillary refill time']), tone: 'green' }],
          ['<strong>Tachycardia + weak pulses + prolonged CRT</strong>', { text: bullets(['Hypovolaemic shock — GDV', 'Intussusception', 'Peritonitis']), tone: 'danger' }],
          ['<strong>Bradycardia</strong>', { text: bullets(['Hypoadrenocorticism (hyperkalaemia)', 'Severe vagal response']), tone: 'green' }],
          ['<strong>Pale MM</strong>', { text: 'Blood loss (haematemesis / melaena) or hypovolaemic shock', tone: 'green' }],
          ['<strong>Icteric MM</strong>', { text: bullets(['Hepatic disease', 'Haemolysis', 'Biliary obstruction']), tone: 'green' }],
          ['<strong>Hyperaemic "injected" MM</strong>', { text: bullets(['Early shock', 'Sepsis', 'SIRS']), tone: 'green' }],
        ],
      },
      {
        kind: 'gridTable',
        label: 'Abdominal palpation',
        cols: '0.8fr 1.35fr',
        dividers: true,
        headers: ['Finding', { text: 'Points to', tone: 'teal' }],
        rows: [
          ['<strong>Pain / guarding</strong>', { text: bullets(['Pancreatitis', 'Peritonitis', 'Obstruction', 'GDV']), tone: 'warning' }],
          ['<strong>Tympanic distension</strong>', { text: bullets(['GDV', 'Intestinal obstruction — <strong>large breed dog + non-productive retching = emergency, do not delay</strong>']), tone: 'danger' }],
          ['<strong>Cranial abdominal mass</strong>', { text: bullets(['Hepatomegaly', 'Splenomegaly', 'Gastric or pancreatic mass']), tone: 'warning' }],
          ['<strong>Mid-abdominal cylindrical mass</strong>', { text: 'Intussusception — "sausage loop"', tone: 'warning' }],
          ['<strong>Fluid wave</strong>', { text: bullets(['Ascites — hepatic disease', 'Peritonitis', 'Hypoalbuminaemia']), tone: 'warning' }],
          ['<strong>Thickened intestinal loops</strong>', { text: bullets(['IBD', 'Neoplasia', 'Infectious enteritis']), tone: 'warning' }],
        ],
      },
      {
        kind: 'gridTable',
        label: 'Oral cavity · neck · neuro · rectal',
        cols: '0.8fr 1.35fr',
        dividers: true,
        headers: ['Finding', { text: 'Points to', tone: 'teal' }],
        rows: [
          ['<strong>Linear FB under the tongue</strong> (especially 🐱)', { text: 'Intestinal obstruction', tone: 'danger' }],
          ['<strong>Oral ulcers</strong>', { text: bullets(['Uraemia (CKD)', 'Caustic toxin ingestion']), tone: 'danger' }],
          ['<strong>Ptyalism</strong>', { text: bullets(['Nausea', 'Oesophagitis', 'Toxin', 'Pharyngeal disease']), tone: 'danger' }],
          ['<strong>Halitosis</strong>', { text: bullets(['Uraemia', 'Hepatic encephalopathy', 'Oral disease']), tone: 'danger' }],
          ['<strong>🐱 Thyroid nodule (ventral neck)</strong>', { text: 'Hyperthyroidism — a common cause of chronic vomiting in cats', tone: 'warning' }],
          ['<strong>Submandibular lymphadenopathy</strong>', { text: bullets(['Neoplasia', 'Infection', 'Lymphoma']), tone: 'warning' }],
          ['<strong>Head tilt + nystagmus + ataxia</strong>', { text: bullets(['Vestibular disease — idiopathic', 'Otitis interna']), tone: 'violet' }],
          ['<strong>Altered mentation / seizures</strong>', { text: bullets(['Intracranial disease', 'Hepatic encephalopathy', 'Severe uraemia', 'Toxin']), tone: 'violet' }],
          ['<strong>Generalised weakness</strong>', { text: bullets(['Hypoadrenocorticism', 'Hypokalaemia', 'Neuromuscular disease. <em>Primary CNS disease causing vomiting alone is rare</em>']), tone: 'violet' }],
          ['<strong>Rectal: melaena</strong>', { text: bullets(['Upper GI haemorrhage — ulceration', 'Neoplasia']), tone: 'danger' }],
          ['<strong>Rectal: haematochezia</strong>', { text: bullets(['Large bowel involvement — colitis', 'Intussusception']), tone: 'danger' }],
        ],
      },
    ],
    after: [{ kind: 'disclaimer' }],
  },

  dx: {
    title: 'Dx: Vomiting',
    blocks: [
      { kind: 'step', text: '🔬 FIRST-LINE DIAGNOSTICS' },
      { kind: 'row', cols: 2, itemKind: 'check', items: [
        { html: '<strong>🧪 CBC · Serum Chemistry · UA</strong><br><span style="font-size:10.5px;">All vomiting cases — first-line</span>' },
        { html: '<strong>📊 Abdominal Imaging</strong><br><span style="font-size:10.5px;">Radiography + Ultrasound</span>' },
      ] },

      { kind: 'step', text: '🧪 CBC · SERUM CHEMISTRY · URINALYSIS', noArrowAfter: true },
      {
        kind: 'gridTable',
        label: 'Haematology',
        cols: '0.8fr 1.35fr',
        dividers: true,
        headers: ['Finding', { text: 'Points to', tone: 'teal' }],
        rows: [
          ['<strong>Leucopenia</strong>', { text: 'Parvovirus / panleukopenia — young unvaccinated', tone: 'teal' }],
          ['<strong>Neutrophilia</strong>', { text: bullets(['Infection', 'Peritonitis', 'Pyometra']), tone: 'teal' }],
          ['<strong>Eosinophilia + absent stress leukogram</strong>', { text: bullets(['Hypoadrenocorticism; also parasites', 'Eosinophilic disease']), tone: 'teal' }],
          ['<strong>Regenerative anaemia</strong>', { text: 'GI haemorrhage', tone: 'teal' }],
          ['<strong>Thrombocytopenia</strong>', { text: bullets(['DIC', 'Immune-mediated thrombocytopenia']), tone: 'teal' }],
        ],
      },
      {
        kind: 'gridTable',
        label: 'Biochemistry & urinalysis',
        cols: '0.8fr 1.35fr',
        dividers: true,
        headers: ['Finding', { text: 'Points to', tone: 'teal' }],
        rows: [
          ['<strong>↑ BUN / Cr + low USG</strong>', { text: bullets(['CKD', 'AKI']), tone: 'teal' }],
          ['<strong>↑ ALT / ALP / GGT</strong>', { text: 'Hepatobiliary disease', tone: 'teal' }],
          ['<strong>Na:K ratio &lt;27</strong>', { text: 'Hypoadrenocorticism — confirm with ACTH stimulation', tone: 'danger' }],
          ['<strong>Persistent hyperglycaemia + glucosuria, no ketones</strong>', { text: 'Diabetes mellitus', tone: 'teal' }],
          ['<strong>Hyperglycaemia + ketonuria</strong>', { text: 'DKA', tone: 'danger' }],
          ['<strong>↑ Total Ca²⁺</strong>', { text: bullets(['Neoplasia', 'Hypoadrenocorticism', 'Hypervitaminosis D']), tone: 'teal' }],
          ['<strong>Hypoalbuminaemia</strong>', { text: bullets(['Protein-losing enteropathy', 'Hepatic failure']), tone: 'teal' }],
          ['<strong>USG &lt;1.030 in a dehydrated dog</strong>', { text: bullets(['CKD', 'Hypoadrenocorticism', 'Diabetes insipidus', 'Pyometra']), tone: 'teal' }],
          ['<strong>Glucosuria without hyperglycaemia</strong>', { text: 'CKD (Fanconi)', tone: 'teal' }],
          ['<strong>Bilirubinuria</strong>', { text: 'Hepatobiliary disease', tone: 'teal' }],
        ],
      },

      { kind: 'step', text: '📊 ABDOMINAL IMAGING', noArrowAfter: true },
      {
        kind: 'gridTable',
        label: 'Survey radiograph (right lateral + VD)',
        cols: '0.8fr 1.35fr',
        dividers: true,
        headers: ['Finding', { text: 'Means', tone: 'teal' }],
        rows: [
          ['<strong>Gas pattern</strong>', { text: 'Dilated loops proximal to obstruction — "stacked" appearance', tone: 'teal' }],
          ['<strong>Radiopaque FB</strong>', { text: 'Foreign body', tone: 'teal' }],
          ['<strong>Gastric compartmentalisation</strong> (double bubble, right lateral)', { text: '<strong>GDV</strong>', tone: 'danger' }],
          ['<strong>Free peritoneal gas</strong>', { text: 'Perforation', tone: 'danger' }],
          ['<strong>Organomegaly / abdominal mass</strong>', { text: bullets(['Hepatomegaly', 'Splenomegaly', 'Mass']), tone: 'teal' }],
          ['<strong>Reduced serosal detail</strong>', { text: 'Peritoneal effusion or emaciation', tone: 'teal' }],
        ],
      },
      {
        kind: 'gridTable',
        label: 'Abdominal ultrasound',
        cols: '0.8fr 1.35fr',
        dividers: true,
        headers: ['Finding', { text: 'Means', tone: 'teal' }],
        rows: [
          ['<strong>Intestinal wall layering</strong>', { text: bullets(['Loss → neoplasia', 'Preserved but thickened → IBD / enteritis']), tone: 'teal' }],
          ['<strong>"Bullseye" / "target" sign</strong>', { text: 'Intussusception', tone: 'teal' }],
          [bullets(['<strong>Pancreatic enlargement</strong>', '<strong>Altered echogenicity</strong>', '<strong>Peripancreatic fat saponification</strong>']), { text: 'Pancreatitis', tone: 'teal' }],
          [bullets(['<strong>Hepatic</strong>', '<strong>Splenic</strong>', '<strong>Adrenal lesions</strong>']), { text: 'Organ-specific disease', tone: 'teal' }],
          ['<strong>Mesenteric lymphadenopathy</strong>', { text: 'IBD vs lymphoma', tone: 'teal' }],
          ['<strong>Free abdominal fluid</strong>', { text: bullets(['Characterise — ascites', 'Exudate', 'Haemorrhage']), tone: 'teal' }],
        ],
      },

      { kind: 'step', text: '🔍 FURTHER INVESTIGATION — SECONDARY / EXTRA-GI', noArrowAfter: true },
      {
        kind: 'gridTable',
        cols: '0.8fr 1.35fr',
        dividers: true,
        headers: ['Abnormality', { text: 'Diagnosis → next step', tone: 'teal' }],
        rows: [
          ['<strong>↑ BUN / Cr + low USG</strong>', { text: bullets(['Urine culture', 'UPC ratio', 'Renal imaging'], { lead: '<strong>Renal disease</strong>' }), tone: 'teal' }],
          ['<strong>↑ ALT / ALP / GGT</strong>', { text: bullets(['Bile acids', 'Abdominal US', 'Liver biopsy'], { lead: '<strong>Hepatobiliary disease</strong>' }), tone: 'teal' }],
          [bullets(['<strong>Na:K &lt;27</strong>', '<strong>Absent stress leukogram</strong>', '<strong>Eosinophilia in a sick dog</strong>']), { text: bullets(['Check basal cortisol', 'If low or suspicion remains → ACTH stimulation test. <em>Atypical Addison\'s: Na:K normal — do not exclude on electrolytes alone</em>'], { lead: '<strong>Hypoadrenocorticism</strong>' }), tone: 'danger' }],
          ['<strong>Persistent hyperglycaemia + glucosuria, no ketones</strong>', { text: bullets(['Fructosamine', 'Urinalysis + culture', 'Start insulin + diet'], { lead: '<strong>Diabetes mellitus</strong>' }), tone: 'teal' }],
          ['<strong>Hyperglycaemia + ketonuria</strong>', { text: bullets(['Blood gas', 'Fluid therapy', 'Insulin protocol'], { lead: '<strong>DKA</strong>' }), tone: 'danger' }],
          ['<strong>↑ Total Ca²⁺</strong>', { text: bullets(['PTH', 'PTHrP', 'Vitamin D metabolites', 'Thoracic imaging'], { lead: '<strong>Hypercalcaemia workup</strong>' }), tone: 'teal' }],
          ['<strong>🐱 ↑ T4</strong>', { text: bullets(['Confirm', 'Recheck in 3 weeks if equivocal'], { lead: '<strong>Hyperthyroidism</strong>' }), tone: 'teal' }],
          ['<strong>↑ cPLI / fPLI</strong>', { text: bullets(['Imaging', 'Supportive care'], { lead: '<strong>Pancreatitis</strong>' }), tone: 'teal' }],
          ['<strong>↓ Albumin + ↓ Globulin</strong>', { text: bullets(['Panhypoproteinaemia = PLE', 'Investigate intestinal vs hepatic origin'], { lead: '<strong>PLE / hepatic failure</strong>' }), tone: 'teal' }],
        ],
      },
      { kind: 'note', html: `Secondary cause confirmed → investigate the primary condition. <strong>Not all extra-GI vomiting requires a GI workup.</strong>` },

      { kind: 'step', text: '🔍 FURTHER INVESTIGATION — IF PRIMARY GI SUSPECTED<br><span style="font-size:10px;font-weight:400;opacity:.85;">When: first-line diagnostics normal or non-diagnostic · chronic or refractory</span>', noArrowAfter: true },
      {
        kind: 'gridTable',
        cols: '0.8fr 1.35fr',
        dividers: true,
        headers: ['Test', { text: 'Detail', tone: 'teal' }],
        rows: [
          ['<strong>fPLI / cPLI</strong>', { text: 'Pancreatitis — especially if imaging is equivocal', tone: 'teal' }],
          ['<strong>Serum T4</strong>', { text: bullets(['Hyperthyroidism — 🐱 any age', 'Atypical presentations possible']), tone: 'teal' }],
          ['<strong>Resting cortisol ± ACTH stimulation</strong>', { text: bullets(['Atypical Addison\'s — absent stress leukogram', 'Eosinophilia in a sick dog']), tone: 'teal' }],
          ['<strong>Cobalamin + folate</strong>', { text: bullets(['SI disease indicator — cobalamin low in EPI', 'Severe IBD', 'Ileal disease']), tone: 'teal' }],
          ['<strong>Fasting gastrin</strong>', { text: bullets(['Gastrinoma / Zollinger-Ellison — refractory ulcers', 'Profound acid hypersecretion']), tone: 'teal' }],
          ['<strong>Bile acids ± plasma ammonia</strong>', { text: bullets(['Hepatic function', 'PSVA']), tone: 'teal' }],
          ['<strong>Dietary trial (4–8 weeks)</strong>', { text: 'Exclusive novel protein or hydrolysed diet — <strong>no treats, chews, or flavoured medications</strong>', tone: 'teal' }],
          ['<strong>Endoscopy + biopsy</strong>', { text: bullets(['Mucosal assessment — chronic gastritis', 'IBD', 'Early neoplasia. Full-thickness preferred for deeper infiltrates']), tone: 'teal' }],
        ],
      },
      { kind: 'lesionLink', loc: 'LOC-GI-UPPER', name: 'Primary GI lesions', noArrowAfter: true },
      { kind: 'lesionLink', loc: 'LOC-GI-SECONDARY', name: 'Secondary / extra-GI causes', tone: 'secondary' },
    ],
    after: [
      {
        kind: 'callout',
        tone: 'danger',
        title: '⚠️ RED FLAGS — URGENT WORKUP',
        items: [
          `Haematemesis`,
          `Projectile vomiting`,
          `Acute abdomen + guarding`,
          `Tympanic distension + non-productive retching (GDV)`,
          `Young unvaccinated (parvo)`,
          `Intact female (pyometra)`,
          `Known toxin/FB ingestion`,
          `Collapse or hypoperfusion`,
        ],
      },
      { kind: 'disclaimer' },
    ],
  },

  },
}
