import { defineConfig } from '@playwright/test'

/**
 * Visual-regression guardrail for the STYLE_MIGRATION work (Phase 0).
 *
 * Every later phase must produce an empty visual diff against these baselines
 * in BOTH theme states. The webServer builds the app with NEXT_PUBLIC_CONVEX_URL
 * unset (no auth, localStorage notes) into an isolated .next-pw dir so it never
 * fights a running `next dev` server, then serves it with `next start`.
 *
 * BASELINE OWNERSHIP — read before regenerating anything.
 *
 * A PNG baseline is tied to the font stack that rendered it. Linux and macOS
 * rasterize text differently, and that shifts line height down a 4000px page far
 * past maxDiffPixelRatio, so ONE baseline set cannot serve both. Worse, two
 * different Macs are both `darwin`: platform-scoping alone still lets them
 * overwrite each other, and a 400KB PNG is a merge conflict git cannot resolve.
 *
 * So exactly one set is authoritative and committed: `__screenshots__/linux/`,
 * generated by the ubuntu runner via the `visual-baselines` workflow
 * (Actions → Update visual baselines → Run workflow). No developer machine ever
 * writes it. That is what CI gates on.
 *
 * `__screenshots__/darwin/` is your own local guardrail and is GITIGNORED, so
 * the two desktops never fight over it. Regenerate yours freely:
 *
 *   npx playwright test --update-snapshots
 *
 * A local run that goes red tells you something moved; the linux set decides
 * whether it lands.
 */
const PORT = Number(process.env.PW_PORT ?? 3456)

export default defineConfig({
  testDir: './tests/visual',
  // Snapshots are the deliverable — keep them next to the spec, one directory
  // per OS so the committed linux set and a local darwin set never collide.
  snapshotPathTemplate: '{testDir}/__screenshots__/{platform}/{arg}{ext}',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: 0,
  workers: 1,
  reporter: [['list']],
  // A little tolerance for sub-pixel font AA differences; styling regressions
  // move far more pixels than this.
  expect: {
    toHaveScreenshot: { maxDiffPixelRatio: 0.01, animations: 'disabled' },
  },
  use: {
    baseURL: `http://localhost:${PORT}`,
    reducedMotion: 'reduce',
    colorScheme: 'no-preference',
  },
  projects: [
    {
      // Deterministic chromium at an iPhone-class mobile viewport. (Not the
      // bundled iPhone device descriptor, which forces the webkit engine.)
      name: 'mobile',
      use: {
        browserName: 'chromium',
        viewport: { width: 390, height: 844 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
      },
    },
  ],
  webServer: {
    // CI builds in its own step so a slow cold build cannot eat this timeout and
    // report as a server-start failure; locally we build here for one command.
    command: process.env.CI
      ? `NEXT_PUBLIC_CONVEX_URL= NEXT_DIST_DIR=.next-pw npx next start -p ${PORT}`
      : `NEXT_PUBLIC_CONVEX_URL= NEXT_DIST_DIR=.next-pw npx next build && NEXT_PUBLIC_CONVEX_URL= NEXT_DIST_DIR=.next-pw npx next start -p ${PORT}`,
    url: `http://localhost:${PORT}`,
    timeout: 180_000,
    // Always launch our own ClinIQ server (a fresh build) — never reuse whatever
    // happens to be on the port, and never serve a stale build after edits.
    reuseExistingServer: false,
    stdout: 'pipe',
    stderr: 'pipe',
  },
})
