// Tab-1 (Diagnostic approaches) home cards — extracted byte-exact from the
// legacy renderLesionHome (cliniqApp.ts) to preserve emoji/variation selectors.

export const DX_HOME_CARDS = [
  { sign: "encephalopathy", icon: "🧬", title: "Acute Encephalopathy", sub: "Stepwise diagnostic workup" },
  { sign: "myelopathy", icon: "🦴", title: "Acute Myelopathy", sub: "Stepwise diagnostic workup" },
  { sign: "vestibular", icon: "🌀", title: "Acute Vestibular", sub: "Stepwise diagnostic workup" },
  { sign: "abnormal-pupil", icon: "🔵", title: "Anisocoria / Abnormal Pupil", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "anorexia", icon: "🍽️", title: "Anorexia / Hyporexia", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "ataxia", icon: "🚶", title: "Ataxia", sub: "Dog + Cat · Stepwise diagnostic workup" },
  { sign: "bleeding", icon: "🔴", title: "Bleeding / Petechiae / Ecchymoses", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "blind-eye", icon: "⚫", title: "Blind Eye / Acute Vision Loss", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "constipation", icon: "💩", title: "Constipation / Tenesmus", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "coughing", icon: "🫁", title: "Coughing", sub: "Stepwise diagnostic workup" },
  { sign: "cyanosis", icon: "🫁", title: "Cyanosis", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "diarrhoea", icon: "💩", title: "Diarrhoea", sub: "Dog + Cat · Small bowel vs large bowel diagnostic approach" },
  { sign: "dysphagia", icon: "😮", title: "Dysphagia / Gagging", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "dyspnoea", icon: "🌬️", title: "Dyspnoea", sub: "Dog 🐕 + Cat 🐱 · History · Exam · Diagnostics" },
  { sign: "epistaxis", icon: "👃", title: "Epistaxis", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "fever", icon: "🌡️", title: "Fever / FUO", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "haematuria", icon: "🩸", title: "Haematuria", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "heart-murmur", icon: "🫀", title: "Heart Murmur", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "jaundice", icon: "🟡", title: "Jaundice", sub: "Dog + Cat · Stepwise diagnostic workup" },
  { sign: "melena", icon: "🩸", title: "Melena / Haematochezia", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "oedema", icon: "🫧", title: "Peripheral Oedema", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "pale-gums", icon: "🩸", title: "Pale Mucous Membranes", sub: "Stepwise diagnostic workup" },
  { sign: "pollakiuria", icon: "🚽", title: "Pollakiuria / Stranguria", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "polyphagia", icon: "🍖", title: "Polyphagia", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "pupd", icon: "💧", title: "Polyuria / Polydipsia", sub: "Dog + Cat · Stepwise diagnostic workup" },
  { sign: "red-eye", icon: "👁️", title: "Red Eye", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "regurgitation", icon: "🔄", title: "Regurgitation", sub: "Dog + Cat · Stepwise diagnostic workup" },
  { sign: "seizures", icon: "🧠", title: "Seizures", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "sneezing", icon: "🤧", title: "Sneezing", sub: "Stepwise diagnostic workup" },
  { sign: "swollen-joints", icon: "🦵", title: "Swollen Joints", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "syncope", icon: "😵", title: "Syncope", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "tremors", icon: "〰️", title: "Tremors", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "vomiting", icon: "🤢", title: "Vomiting", sub: "Dog + Cat · Stepwise diagnostic workup" },
  { sign: "weakness", icon: "⚡", title: "Weakness / Collapse", sub: "Dog + Cat · Stepwise diagnostic workup" },
  { sign: "weight-loss", icon: "📉", title: "Weight Loss", sub: "Dog + Cat · History · Exam · Diagnostics" },
  { sign: "wet-eye", icon: "💧", title: "Wet Eye / Epiphora", sub: "Dog + Cat · History · Exam · Diagnostics" },
] as const
