// ── Acute Myelopathy / Spinal-cord-localisation flowchart (data) ────────────
import type { FlowPage } from '../flowTypes'

const myelopathyEntry: FlowPage = {
  id: 'myelopathy',
  title: 'Acute Myelopathy',
  blocks: [
    { kind: 'node', variant: 'entry', text: '🦴 ACUTE MYELOPATHY — NEUROLOGICAL LOCALISATION' },
    {
      kind: 'node',
      variant: 'step',
      text: 'Perform head-to-tail neurological examination — compare findings to table below to localise lesion',
      sub: 'Assess in order: mentation → pain on palpation → gait → postural reactions → spinal reflexes → special tests',
    },
    {
      kind: 'table',
      scroll: true,
      minWidth: 560,
      gap: 8,
      title: 'Neurological Localisation',
      cols: 'auto repeat(5, 1fr)',
      headers: [
        'Finding',
        { text: 'C1–C5', tone: 'green' },
        { text: 'C6–T2', tone: 'indigo' },
        { text: 'T3–L3', tone: 'warning' },
        { text: 'L4–S3', tone: 'violet' },
        { text: 'S2–Ca5', tone: 'purple' },
      ],
      rows: [
        { section: 'General & Gait' },
        ['Pain', 'Cervical low head · stiff neck', 'Caudal cervical / thoracic inlet', 'Thoracolumbar kyphosis', 'Lumbosacral pain', 'Lumbosacral / perineal pain'],
        ['Gait', 'Tetraparesis (all 4 limbs)', 'Tetraparesis (FL worse)', 'Paraparesis (HL; FL normal)', 'Paraparesis / monoparesis (HL)', 'Paraparesis (HL + tail)'],
        { section: 'CP & Muscle Tone' },
        ['Forelimb CP', 'Deficient', 'Deficient', 'Normal', 'Normal', 'Normal'],
        ['Hindlimb CP', 'Deficient', 'Deficient', 'Deficient', 'Deficient', 'Deficient'],
        ['FL tone', 'UMN spastic / ↑', 'LMN flaccid · atrophy', 'Normal', 'Normal', 'Normal'],
        ['HL tone', 'UMN spastic / ↑', 'UMN spastic / ↑', 'UMN spastic / ↑', 'LMN flaccid / ↓', 'LMN flaccid / ↓'],
        { section: 'Spinal Reflexes' },
        ['Biceps (C6–C8)', '↑ / Normal', '↓ / Absent', 'Normal', 'Normal', 'Normal'],
        ['Triceps (C7–T1)', '↑ / Normal', '↓ / Absent', 'Normal', 'Normal', 'Normal'],
        ['FL withdrawal', '↑ / Normal', '↓ / Absent', 'Normal', 'Normal', 'Normal'],
        ['Patellar (L3–L4)', '↑ / Normal', '↑ / Normal', '↑ / Normal', '↓ / Absent', 'Normal'],
        ['HL withdrawal', '↑ / Normal', '↑ / Normal', '↑ / Normal', '↓ / Absent', 'Absent'],
        ['Perineal / anal', 'Normal', 'Normal', 'Normal', '↓ / Absent', 'Absent'],
        { section: 'Special Tests' },
        ['Cutaneous trunci', 'Present bilateral', '↓/absent if C8–T1', 'Absent caudal (cutoff ≈1–2 segs)', 'Normal', 'Normal'],
        ["Horner's", 'Normal', 'Present (T1–T3)', 'Normal', 'Normal', 'Normal'],
        ['Schiff-Sherrington', 'Normal', 'Normal', '± FL ext · HL paralysis (severe)', 'Normal', 'Normal'],
        ['Bladder', 'UMN spastic · large', 'UMN spastic', 'UMN spastic · reflexic', 'LMN flaccid · easy', 'LMN flaccid · easy'],
        ['Tail tone', 'Normal', 'Normal', 'Normal', '↓ reduced', 'Flaccid'],
      ],
    },
    {
      kind: 'table',
      scroll: true,
      minWidth: 360,
      gap: 8,
      title: 'Injury Grading',
      cols: 'auto auto 1fr 1fr',
      headers: [
        'Grade',
        'Description',
        { text: 'Thoracolumbar', tone: 'warning' },
        { text: 'Cervical', tone: 'green' },
      ],
      rows: [
        ['1', 'Pain only; neurologically intact', 'Spinal pain; normal neurologic function', 'Spinal pain; normal neurologic function'],
        ['2', 'Ambulatory paresis; CP deficits ± ataxia', 'Ambulatory paraparesis + HL ataxia', 'Ambulatory tetraparesis + tetra-ataxia'],
        [{ text: '3', tone: 'warning' }, 'Non-ambulatory paresis; voluntary movement present', 'Non-ambulatory paraparesis', 'Non-ambulatory tetraparesis'],
        [{ text: '4', tone: 'orange' }, 'Paralysis; DPP intact', 'Paraplegia; intact pain perception', 'Tetraplegia; normal ventilation'],
        [{ text: '5', tone: 'danger' }, 'Paralysis; DPP <strong>absent</strong>', 'Paraplegia; <strong>absent</strong> DPP in HLs + tail', 'Tetraplegia; <strong>hypoventilation</strong>'],
      ],
    },
    {
      kind: 'callout',
      tone: 'danger',
      gap: 10,
      connectAfter: false,
      title: '⚠️ DEEP PAIN PERCEPTION — most important prognostic indicator',
      html: 'Test by applying firm pressure to digit with haemostat (separate from withdrawal — look for conscious response: turning head, vocalisation, behavioural change).<br><strong>DPP absent:</strong> Thoracolumbar &lt;48 h → 50–60% recovery with decompression; &gt;48 h → poor prognosis (myelomalacia risk). Grade 5 IVDE (IVDD type III): 10–13% risk of progressive myelomalacia (fatal).',
    },
    {
      kind: 'table',
      scroll: true,
      minWidth: 400,
      gap: 8,
      title: 'Recovery of Function — Thoracolumbar (% ambulatory)',
      cols: 'auto 1fr 1fr 1fr 1fr',
      headers: [
        'Grade',
        { text: 'IVDE (IVDD III) Surgical', tone: 'warning' },
        'IVDE (IVDD III) Medical',
        { text: 'ANNPE', tone: 'green' },
        { text: 'FCE', tone: 'indigo' },
      ],
      rows: [
        ['2', '95–100%', '75%', '100%', '100%'],
        ['3', '95–100%', '75%', '100%', '100%'],
        [{ text: '4', tone: 'warning' }, '>90%', '50%', '56%*', '70%*'],
        [{ text: '5', tone: 'danger' }, '58%†', '<10%', '<10%', '10%'],
      ],
      footnote: '*Partial urinary/faecal incontinence may persist. †Increases to 69% including recovery without pain perception.',
    },
    { kind: 'node', variant: 'step', text: 'NAVIGATE TO LESION DATABASE' },
    {
      kind: 'categoryGrid',
      columns: [
        { cat: 'Cervical (C1–T2)', tone: 'green', tiles: [{ label: 'Tetraparesis', link: { to: 'lesion', loc: 'LOC-MY-CERV', name: 'Cervical' } }] },
        { cat: 'Thoracolumbar (T3–L3)', tone: 'warning', tiles: [{ label: 'Paraparesis', link: { to: 'lesion', loc: 'LOC-MY-TL', name: 'Thoracolumbar' } }] },
        { cat: 'L4–S3', tone: 'violet', tiles: [{ label: 'LMN paraparesis', link: { to: 'lesion', loc: 'LOC-MY-L4S3', name: 'L4–S3' } }] },
        { cat: 'S2–Ca5 (conus)', tone: 'purple', tiles: [{ label: 'Cauda equina', link: { to: 'lesion', loc: 'LOC-MY-CONUS', name: 'S2–Ca5' } }] },
      ],
    },
    { kind: 'disclaimer' },
  ],
}

export const myelopathyFlows: FlowPage[] = [myelopathyEntry]
